export const cuisineList = [
    // Famous Indian Dishes
    "Butter Chicken",
    "Chicken Tikka Masala",
    "Biryani",
    "Dosa",
    "Idli",
    "Vada",
    "Paneer Tikka",
    "Rogan Josh",
    "Chole Bhature",
    "Samosa",
    "Tandoori Chicken",
    "Masala Dosa",
    "Sambar",
    "Rasam",
    "Pani Puri",
    "Dal Makhani",
    "Palak Paneer",
    "Aloo Gobi",
    "Naan",
    "Gulab Jamun",
    "Lassi",
  
    // Universally Famous Dishes
    "Pizza",
    "Burger",
    "Pasta",
    "Sushi",
    "Tacos",
    "Steak",
    "Salad",
    "Chocolate Cake",
    "Ice Cream",
    "French Fries",
    "Fried Chicken",
    "Spaghetti",
    "BBQ Ribs",
    "Caesar Salad",
    "Hot Dog",
    "Sandwich",
    "Ramen",
    "Dim Sum",
    "Paella",
    "Croissant",
    "Falafel",
    "Shawarma",
    "Hummus",
    "Pho",
  ];
  